log_base_path: ~/Documents/STOPME/logs  # Path where logs are saved. User folder is automatically detected
log_actuation_details: false            # Log actuation details: duration, duty cycle, intensity, pattern ecc...
enable_system_log: true                 # Create/Log system status messages

debug_system_console: true   # Choose to print system events on the console
debug_event_console: true   # Choose to print events on the console

metamotion:
  scan_timeout: 2             # First BLE scan duration in seconds
  fast_retry_attempts: 5      # Number of fast retries after a disconnection
  retry_interval: 5           # Wait time between fast retries
  retry_sleep: 60             # Wait time between subsequent retries

speaker:
  scan_timeout: 5             # First scan duration in seconds
  fast_retry_attempts: 5      # Number of fast retries after a disconnection
  retry_interval: 10           # Wait time between fast retries
  retry_sleep: 60            # Wait time between subsequent retries

led_strip:
  scan_timeout: 10            # First scan duration in seconds
  fast_retry_attempts: 5      # Number of fast retries after a disconnection
  retry_interval: 5           # Wait time between fast retries
  retry_sleep: 60             # Wait time between subsequent retries

bluecoins:
  - id: bc_temp
    feature: temperature
    thresholds:
      low: 30
      medium: 32
      high: 34

  - id: bc_activity
    feature: activity

  - id: bc_inertial
    feature: inertial